language: r

before_install:
  - tlmgr install extsizes

r_check_args: "--no-manual --ignore-vignettes"

r_build_args: "--no-manual --no-build-vignettes"

r_packages:
  - covr
  
after_success:
  - Rscript -e 'covr::codecov()'
